config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  get "users/index"
  #get 'home/index'
  #devise_for :users
  resources :tasks
  resources :users, only: [:index]
  devise_for :users
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  end


  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :name, :due_date, :description, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :confirmable, :trackable  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
         
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_locale

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :dob])

        devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, 
        :dob, :email, :password])
        end
        
        def default_url_options
            {locale: I18n.locale}
        end
        def set_locale
            I18n.locale = extract_locale || I18n.default_locale
        end
        
        def extract_locale
            parsed_locale = params[:locale]
            I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  protect_from_forgery with: :null_session
  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
    respond_to do |format|
      format.html
      format.pdf do
          
         render pdf: "task",
                page_size: 'A4',
                template: "tasks/index",
                layout: "application",
                orientation: "Landscape",
                lowquality: true,
                zoom: 1,
                dpi: 75
               
               #inline: "<% @tasks.each do |p| %><p><%= p.name %></p><% end %>"
      end
        format.csv 
    end  
  end

  # GET /tasks/1 or /tasks/1.json
  def show
     
  end      

  # GET /tasks/new
  def new
    #@task = Task.new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    #@task = current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        #UserMailer.with(user:current_user, task: @task).user_created.deliver_now
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.js
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end
 
  def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      redirect_to tasks_path, notice: "Not Authorized to edit this task" if @task.nil?
  end
  helper_method :correct_user
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :due_date, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
      @user = User.all
     
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<style>
.button {
  background-color: hsl(0, 100%, 70%);;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
</style>

<div class="home">
    <h1> <%= t 'hello' %> </h1>
    <br> <br>
    
   <div class="button"> <%= link_to t('task'), tasks_path %> </div>
   <div class="button"> <%= link_to t('user'), users_path %> </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <style>
.button {
  background-color: hsl(0, 100%, 70%);;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
  </head>

  <body>
      <div class="button"> <%= link_to t('home'), root_path %> </div>
      <div class="button"> <%= link_to t('sign_in'), new_user_session_path %> </div>
      
      <% if user_signed_in? %>
      
      <div class="button"> <%= link_to t('edit'), edit_user_registration_path %> </div>
        
       <div class="button"> <%= link_to t('sign_out'), destroy_user_session_path, data: { turbo_method: :delete } %>  </div>
      <% end %>
    
       <div class="button">  <%= link_to t('sign_up'), new_user_registration_path %>  </div> 
      
      <div class="Enlang"> <%= link_to "English", root_path(locale: :en)%>
      <div class="Rulang"> <%= link_to "Russian", root_path(locale: :ru)%>   
      
     
    
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
      
    <%= yield %>
      
      

      
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true, html: {class: "update"} do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    
    <%= form.number_field :user_id, value: current_user.id, id: :task_user_id, type: :hidden %>
  </div>
  
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit "update", remote: true %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>
    
  <p>
    <strong>User:</strong>
    <%= task.user_id %>
  </p>

</div>

app/views/tasks/create.js.erb
$('#tasks').append("<%= j render @task %>");

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to t('show_task'), @task %> |
  <%= link_to t('back_task'), tasks_path %>
</div>

app/views/tasks/index.csv.erb
<% @tasks.each do |task| %>
<%= name = task.name %>
<%= due_date = task.due_date %>
<%= description = task.description %>
<%= [name.to_s, due_date.to_s, description.to_s].join(";") %>
<% end %>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>



<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to t('show_task'), task %>
      
    </p>
  <% end %>
</div>

<%= link_to t('new_task'), new_task_path %>
<%= link_to t('pdf'), tasks_path(format: :pdf) %>
<%= link_to t('csv'), tasks_path(format: :csv) %>
<%= yield %>

app/views/tasks/index.pdf.erb
<% @tasks.each do |task| %>
<%= name = task.name %>
<%= due_date = task.due_date %>
<%= description = task.description %>
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to t('back_task'), tasks_path %>
</div>

app/views/tasks/pdf.html.erb
# file: rails-generate-pdf/views/layotus/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "invoice" %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/tasks/show.html.erb
<%begin%>
<%if notice>0 %>

<p style="color: green"><%= notice= "Task is updated/Assigned" %></p>
<% else %>
<p style="color: green"><%= notice= "Task is Failed" %></p>
<% end %>
<%rescue%>
<% end %>

<%= render "tasks/task", :task=>@task %>


<div>
  <%= link_to t('edit_task'), edit_task_path(@task) %> |
  <%= link_to t('back_task'), tasks_path %>

  <%= button_to t('des_task'), @task, method: :delete %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users = User.all %>
<% @tasks = Task.all%>
<% @users.each do |user| %>
<h4> User ID: <%= user.id %><br/> </h4> 
<h4> First Name: <%= user.firstname %><br/> </h4>
<h4> Last Name: <%= user.lastname %><br/> </h4> 
<h4> Date of Birth: <%= user.dob %><br/> </h4> 
<h4> Mail ID:  <%= user.email %><br/></h4> 
  <br>
<% end %>